version: 2.1
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/buildpack-deps:stretch

    environment:
      IMAGE_NAME: janwarchol/ci-test
      IMAGE_TAG: ci-build-${CIRCLE_BUILD_NUM}
      DOCKER_LOGIN: janwarchol
      # set DOCKER_PASSWORD in project settings.

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .

      - run:
          name: Push Docker image
          command: |
            docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
            docker push ${IMAGE_NAME}:${IMAGE_TAG}
