version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/buildpack-deps:stretch

    environment:
      IMAGE_NAME: janwarchol/ci-test

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build and push Docker image
          command: |
            TAG="${CIRCLE_BUILD_NUM}"
            docker build -t ${IMAGE_NAME}:$TAG .
            # docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            # docker push circleci/cci-demo-docker:$TAG
