version: 2.1
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/buildpack-deps:stretch

    environment:
      IMAGE_NAME: janwarchol/ci-test

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            docker build -t ${IMAGE_NAME}:ci-build-${CIRCLE_BUILD_NUM} .

      - run:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push ${IMAGE_NAME}:ci-build-${CIRCLE_BUILD_NUM}

workflows:
  do-stuff:
    jobs:
      - build:
          context:
            - jw-default
